<?php
/** @var \Magento\Framework\View\Element\Template $block */

/** @var \WeltPixel\FrontendOptions\Helper\Data $wpHelper */
$wpHelper = $this->helper('WeltPixel\FrontendOptions\Helper\Data');
$cspNonceProvider = $wpHelper->getCspNonceProvider();
?>
<script <?php if ($cspNonceProvider) echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
    require(["jquery"], function ($) {
        $(document).ready(function () {
            let noticeAriaLabelName = "<?= $block->escapeHtml(__('Cookies Restriction Messages')) ?>";
            let minicartAriaLabelName = "<?= $block->escapeHtml(__('Minicart Popup Container')) ?>";
            $('#notice-cookie-block').attr('aria-label', noticeAriaLabelName);

            $('div.block.block-minicart').on('dropdowndialogcreate', function () {
                $(this).parent().attr('aria-label', minicartAriaLabelName);
            });

            $('select.limiter-options').attr('aria-label', '<?= $block->escapeHtml(__('Show per page')) ?>');
            $('td.col.actions').attr('aria-label', '<?= $block->escapeHtml(__('Actions Column')) ?>');
        });
    });
</script>

