<?php
// @codingStandardsIgnoreFile
?>
<?php
$_helper = $this->helper('WeltPixel\GA4\Helper\Data');
$gtmCodeSnippetForHead = $_helper->getGtmCodeSnippetForHead();
$cspNonceProvider = $_helper->getCspNonceProvider();

$pattern = '/<script(.*)>/';
$replacement = '<script ${1}> if (window.ga4AllowServices) {';
$gtmCodeSnippetForHead =  str_replace('</script>', '} </script>', preg_replace($pattern, $replacement, $gtmCodeSnippetForHead));

if ($cspNonceProvider) {
    $gtmCodeSnippetForHead = str_replace('<script', '<script nonce="' . $cspNonceProvider->generateNonce() . '" ', $gtmCodeSnippetForHead);
}

?>
<?php if ($_helper->isEnabled()) : ?>
    <?php echo $gtmCodeSnippetForHead; ?>
<?php endif; ?>
