<?php
$wpHelper = $this->helper('WeltPixel\CategoryPage\Helper\Data');
?>
<script>
    requirejs(['jquery'],
        function   ($) {
            $(window).bind("pageshow", function(event) {
                if (event.originalEvent.persisted) {
                    $('img[data-origsrc]').each(function() {
                        if ($(this).attr('data-tmp')) {
                            $(this).attr('src', ($(this).attr('data-origsrc')));
                        }
                    });
                }
            });
        });
</script>
<?php if ($wpHelper->disableMobileDoubleClick()) : ?>
<script>
    requirejs(['jquery', 'WeltPixel_CategoryPage/js/fastclick' ],
        function   ($, attachFastClick) {
            $(function() {
                attachFastClick.attach(document.body);
            });
        });
</script>
<?php endif; ?>
