<?php
$_helper = $this->helper('WeltPixel\QuickCart\Helper\Data');
$cspNonceProvider = $_helper->getCspNonceProvider();
?>
<?php if ($_helper->quicartIsEnabled()): ?>
    <script <?php if ($cspNonceProvider) echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
        window.openMinicart = '<?php /* @escapeNotVerified */ echo $_helper->openMinicart(); ?>';
        window.shouldOpenMinicart = '1';
        window.openMinicartDisplayOptions = '<?php /* @escapeNotVerified */ echo $_helper->getQuickCartDisplayOptions(); ?>';
        requirejs(['jquery', 'weltpixel_quickcart' ], function($, quickcart) {
            $(document).ready(function() {
                var mobileBreakpoint = <?= ($_helper->getMobileBreakPoint() !== '' ? $_helper->getMobileBreakPoint() : '768' ); ?>;
                quickcart.initialize(mobileBreakpoint);
            });
        });
    </script>
<?php endif; ?>
