<?php
/** @var $wpHelper \WeltPixel\CustomHeader\Helper\Data */
$wpHelper = $this->helper('WeltPixel\CustomHeader\Helper\Data');
$cspNonceProvider = $wpHelper->getCspNonceProvider();
?>
<script <?php if ($cspNonceProvider) echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
    require(['jquery', 'WeltPixel_CustomHeader/js/header_js'], function ($, Header) {
        $(document).ready(function () {
            Header.action();
        });

        $(window).on('load',function () {
            Header.action();
        });

        var reinitTimer;
        $(window).on('resize', function () {
            clearTimeout(reinitTimer);
            reinitTimer = setTimeout(function() {Header.action();}, 100);
        });
    });
</script>
