<?php
$_helper = $this->helper('WeltPixel\FrontendOptions\Helper\Data');
$_designeElementsHelper = $this->helper('WeltPixel\DesignElements\Helper\Data');
$cspNonceProvider = $_designeElementsHelper->getCspNonceProvider();

if ($_designeElementsHelper->isResponsiveHelpersEnabled()) :
?>
<script <?php if ($cspNonceProvider) echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
require(['jquery', 'designelements_base' ],
function   ($, SEMICOLONBASE) {
    var options = <?php echo $_helper->getBreakPointsJson(); ?>;
    $(document).ready( SEMICOLONBASE.widget.init(options) );
    $(window).on( 'resize', function() {
        var t = setTimeout( function(){
            SEMICOLONBASE.widget.responsiveWpClasses();
        }, 500 );
    });
});
</script>
<?php endif; ?>
<script <?php if ($cspNonceProvider) echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
    window.Pearl = window.Pearl || {};
    window.Pearl.scrollCollapsibleToTop = <?php echo $_designeElementsHelper->getCollapsibleWidgetTopJump(); ?>;
</script>
