<?php
/** @var $wpHelper \WeltPixel\DesignElements\Helper\Data */
$wpHelper = $this->helper('WeltPixel\DesignElements\Helper\Data');
$cspNonceProvider = $wpHelper->getCspNonceProvider();
?>
<script <?php if ($cspNonceProvider) echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
require(['jquery', 'load_parallax' ],
function   ($, SEMICOLONPARALLAX) {
    $(document).ready( SEMICOLONPARALLAX.widget.init() );
});
</script>
