<?php
/** @var $wpHelper \WeltPixel\DesignElements\Helper\Data */
$wpHelper = $this->helper('WeltPixel\DesignElements\Helper\Data');
$cspNonceProvider = $wpHelper->getCspNonceProvider();
?>
<script <?php if ($cspNonceProvider) echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
require(['jquery', 'designelements_default' ],
function   ($, SEMICOLONDEFAULT) {
    $(document).ready( SEMICOLONDEFAULT.widget.init() );
    $(window).on( 'resize', function() {
        var t = setTimeout( function(){
            SEMICOLONDEFAULT.widget.dataResponsiveClasses();
            SEMICOLONDEFAULT.widget.dataResponsiveHeights();
            SEMICOLONDEFAULT.widget.verticalMiddle();
            SEMICOLONDEFAULT.widget.fullScreen();
        }, 500 );
    });
});
</script>
