<?php
/** @var $wpHelper \WeltPixel\DesignElements\Helper\Data */
$wpHelper = $this->helper('WeltPixel\DesignElements\Helper\Data');
$cspNonceProvider = $wpHelper->getCspNonceProvider();
?>
<script <?php if ($cspNonceProvider) echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
require(['jquery', 'designelements_default', 'testimonialsGrid' ],
function   ($, SEMICOLONDEFAULT, SEMICOLONSTESTIMONIALSGRID) {
    $(document).ready(function() {
        SEMICOLONDEFAULT.widget.init();
        SEMICOLONSTESTIMONIALSGRID.widget.init();
    });
    $(window).on( 'resize', function() {
        var t = setTimeout( function(){
            SEMICOLONSTESTIMONIALSGRID.widget.testimonialsGrid();
        }, 500 );
    });
});
</script>
