<?php
/** @var $wpHelper \WeltPixel\DesignElements\Helper\Data */
$wpHelper = $this->helper('WeltPixel\DesignElements\Helper\Data');
$cspNonceProvider = $wpHelper->getCspNonceProvider();
?>
<script <?php if ($cspNonceProvider) echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
require(['jquery', 'toggles_accordions_tabs'],
function   ($, SEMICOLONTABS) {
    $(document).ready( SEMICOLONTABS.widget.init() );
    $(window).on( 'resize', function() {
        var t = setTimeout( function(){
                SEMICOLONTABS.widget.tabsJustify();
            }, 500 );
        });
});
</script>
