<?php
    $_helper = $this->helper('WeltPixel\DesignElements\Helper\Data');
    $options = $_helper->getBttOptionsJson();
    $cspNonceProvider = $_helper->getCspNonceProvider();
?>
<button type="button" title="<?php /* @escapeNotVerified */ echo __('Back To Top') ?>" class="btt-button action"></button>

<script <?php if ($cspNonceProvider) echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
    require(['jquery','btt_button'],
        function ($, SEMICOLONBTTBUTTON) {
            var options = '<?php echo $options ?>';
            $(document).ready(
                SEMICOLONBTTBUTTON.widget.init(options)
            );
        });
</script>
