<?php
/** @var $wpHelper \WeltPixel\DesignElements\Helper\Data */
$wpHelper = $this->helper('WeltPixel\DesignElements\Helper\Data');
$cspNonceProvider = $wpHelper->getCspNonceProvider();
?>
<script <?php if ($cspNonceProvider) echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
require(['jquery', 'smooth_scrolling' ],
function   ($, SEMICOLONSMOOTHSCROLL) {
    $(document).ready( SEMICOLONSMOOTHSCROLL.widget.init() );
});
</script>
